### PR TITLE
studio: Support `DVC_` env vars.

### PR DESCRIPTION
**Pull request by daavoo**
Per https://github.com/iterative/dvc-studio-client/pull/28

### CODE REVIEW

**Comment by skshetry** [comment]
Should we wait for dvc to release? I am worried if we will get into some conflicts here.

**Review by skshetry — APPROVED** [review]

**Comment by skshetry** [comment]
Maybe not. 
https://github.com/iterative/dvc/blob/dd3deb6cbd00ab19f60fb63d7a3ab154242a9826/pyproject.toml#L40

**Comment by daavoo** [comment]
> Maybe not. https://github.com/iterative/dvc/blob/dd3deb6cbd00ab19f60fb63d7a3ab154242a9826/pyproject.toml#L40

wait, how does your DVC P.R. work without bumping?

**Comment by skshetry** [comment]
As dvc has to make decisions also based on config, there was no point to spread out logic into two places.

```python
if not token := (
      os.environ.get(DVC_STUDIO_TOKEN)
      or os.environ.get("STUDIO_TOKEN")
      or config.get("token")
):
  pass
```

If dvclive has to do the same, it might be better to use dvc instead of client (I know you want to reduce dependency on dvc, but we have more bigger issues than Studio client there).

**Comment by skshetry** [comment]
Also using env variables are simple enough, that I am fine with whatever you decide: either importing it or redeclaring here.

**Pull request merged**
