### PR TITLE
Removed html from public API

### PR DESCRIPTION
**Pull request by daavoo**
* [X] ❗ I have followed the [Contributing to DVCLive](https://github.com/iterative/dvclive/blob/master/CONTRIBUTING.md) guide.

* [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

Discussed in #128 

`dvc.org` P.R: https://github.com/iterative/dvc.org/pull/2683

### CODE REVIEW

**Review by pared — APPROVED** [review]

**Comment by dberenbaum** [comment]
What if users have dvc installed but aren't running their dvclive code via dvc (running `python train.py` where `train.py` includes `dvclive` calls)? Should dvclive default to generating html unless dvc isn't installed?

**Comment by pared** [comment]
@dberenbaum hmm, if we are considering it, we should make a new issue for that. HTML creation is not available in the current state of dvclive (since #44, where we started to create a signal file for dvc). The mechanism is as follows:


- dvclive detects it is in `dvc` repo
- create signal file
- dvc picks up the file and makes HTML

So, even before this change HTML would not be created without dvc.

**Comment by dberenbaum** [comment]
Sounds good. Makes sense for it to be strictly a benefit of dvc integration. In the early days of dvclive, I think we had plans for it to have more standalone functionality without dvc, but it seems better to focus on the experience with dvc now.

**Comment by pared** [comment]
@dberenbaum you are right, and before #44 we actually used dvc to plot. But in our efforts to make `dvclive` as dependency-less as possible we lost ability to plot "from within" `dvclive`. I might have not stressed that enough before finishing #44 and later it was not brought up.

If we want this we could possibly check if `dvc` is installed and use it for plots. That way we could plot "from within" and not require `dvc` in project requirements.

**Comment by daavoo** [comment]
> @dberenbaum you are right, and before #44 we actually used dvc to plot. But in our efforts to make `dvclive` as dependency-less as possible we lost ability to plot "from within" `dvclive`. I might have not stressed that enough before finishing #44 and later it was not brought up.
> 
> If we want this we could possibly check if `dvc` is installed and use it for plots. That way we could plot "from within" and not require `dvc` in project requirements.

Perhaps having `dvclive.show` and make `dvc` just one of the potential plotting "backends", similar to what has been discussed in https://github.com/iterative/dvclive/issues/61?

**Comment by dberenbaum** [comment]
That's a possibility. For now, IMO it's more important to focus on the experience with DVC, so I'm happy to leave this as is.

**Pull request merged**
