### PR TITLE
frameworks: Don't log `epoch`.

### PR DESCRIPTION
**Pull request by daavoo**

### CODE REVIEW

**Comment by dberenbaum** [comment]
I think I'm missing the context here @daavoo. Why not log epoch?

**Comment by daavoo** [comment]
> I think I'm missing the context here @daavoo. Why not log epoch?

I felt like it is just redundant with the `step`. 
What is the use case of the `epoch` linear plot which is a constant `y=x`?

**Comment by dberenbaum** [comment]
Often the step corresponds to something other than a full epoch (like one batch iteration). I would still want the epoch recorded separately in that case, although I wouldn't want to plot it. I would rather keep recording it and address plotting it elsewhere. If we consolidate the tsv output like in #374, we will have to specify which columns to plot, and we could ignore it there. What do you think?

**Comment by daavoo** [comment]
> Often the step corresponds to something other than a full epoch (like one batch iteration)

From the integrations we provide, I think is only true for PyTorch Lightning.

> I would rather keep recording it and address plotting it elsewhere. If we consolidate the tsv output like in #374, we will have to specify which columns to plot, and we could ignore it there. What do you think?

I still don't undestand how the epoch signal can be used in practice nowadays but removing is not critical to me, so we can wait.

**Comment by dberenbaum** [comment]
🤔 It's possible to log at the batch step level in other frameworks (https://www.tensorflow.org/guide/keras/custom_callback, https://huggingface.co/docs/transformers/v4.25.1/en/main_classes/callback#transformers.TrainerCallback.on_step_end), but this seems too granular, so I agree it's unhelpful.

We could leave it for lightning and drop it for others.

Should/can we rename step to epoch for those other frameworks since technically they tend to use step to refer to batch iterations and epoch to refer to full dataset iterations?

**Pull request closed without merging**
