### PR TITLE
fix(pyproject): proper reference to the lighting extra

### PR DESCRIPTION
**Pull request by shcheklein**
Found a small issue while reviewing https://github.com/iterative/dvclive/pull/749

------------------

- [X] ❗ I have followed the [Contributing to DVCLive](https://github.com/iterative/dvclive/blob/main/CONTRIBUTING.rst)
  guide.

- [X] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by shcheklein** [comment]
Actually, I think it's better to be fixed right in the #749 since we are changing the lighting module there and here CI fails with mypy on it.

**Comment by dberenbaum** [comment]
@shcheklein What issue did you git using `pytorch-lightning`? The codebase tries to be compatible with both `lightning` and `pytorch-lightning`, so wondering if there is something we need to address here.

**Comment by shcheklein** [comment]
I think the `dvclive[all]` just doesn't install it. Since there is not `pytorch-lightning` anymore AFAIR.

**Comment by dberenbaum** [comment]
Okay, I see. It looks like they both still exist but `lightning` is a superset that includes both `pytorch-lightning` and `fabric`. See https://github.com/Lightning-AI/pytorch-lightning/discussions/16688#discussioncomment-6750981.

**Comment by shcheklein** [comment]
To clarify, I think it us:

```
tf = ["tensorflow"]
xgb = ["xgboost"]
lgbm = ["lightgbm"]
huggingface = ["transformers", "datasets"]
catalyst = ["catalyst>22"]
fastai = ["fastai"]
lightning = ["lightning>=2.0", "torch"]
optuna = ["optuna"]
all = [
   "dvclive[image,mmcv,tf,xgb,lgbm,huggingface,catalyst,fastai,lightning,optuna,plots,markdown]"
]
```

mind the `lightning` and it's definition. `all` was referring to non-existent extra in _our_ config ASFAI.

**Comment by dberenbaum** [comment]
🤦 Got it, thanks for the clarification

**Pull request closed without merging**
