### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by dberenbaum**

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
@dberenbaum cleanup test is failing because of merging both #384 and #440 .

**Review by daavoo — APPROVED** [review]
I did not really review in depth the short metric names in `.tsv` but I think it's ok

**Comment by daavoo** [comment]
@dberenbaum Would be great if you can add some short descriptions for the relevant changes in the release notes

**Comment by dberenbaum** [comment]
> I did not really review in depth the short metric names in `.tsv` but I think it's ok

I tried to test it out a bit in VS Code/Studio. Hard to tell with live metrics because I think I'm running into unrelated issues, but nothing looks broken yet.

**Comment by dberenbaum** [comment]
Thanks @daavoo! I will try to log back on in a few hours to do the release.

**Pull request merged**
