### PR TITLE
bump mypy to 0.981, enable recursive type aliases

### PR DESCRIPTION
**Pull request by dtrifiro**

### CODE REVIEW

**Comment by dtrifiro** [comment]
Not sure what's going on, but this is the error (linting session):
```console
nox > safety check --full-report
Unhandled exception happened: 'catalyst'
```

**Review by daavoo — COMMENTED** [review]
I believe we can also remove the 3.10.6 pin on CI as the mypy release is supposed to fix the issue

**Comment by dtrifiro** [comment]
@daavoo the safety session is failing because of a catalyst[dev] dependency (sphinx) with a security vulnerability. I see that catalyst is pinned: `catalyst<=21.12`, do you know why?

**Comment by daavoo** [comment]
> @daavoo the safety session is failing because of a catalyst[dev] dependency (sphinx) with a security vulnerability 🤦‍♀️. I see that catalyst is pinned: `catalyst<=21.12`, do you know why?

I believe because of this https://github.com/iterative/dvclive/issues/219

**Comment by daavoo** [comment]
> @daavoo the safety session is failing because of a catalyst[dev] dependency (sphinx) with a security vulnerability 🤦‍♀️. I see that catalyst is pinned: `catalyst<=21.12`, do you know why?

Vulnerability appears to also affect the latest version so the pin was not really the problem (anyway it is good to update)

**Pull request merged**
