### PR TITLE
tests: Simplify huggingface tests.

### PR DESCRIPTION
**Pull request by daavoo**
Use simple dataset and model from `transformers/tests/trainer`.

### CODE REVIEW

**Review by pared — COMMENTED** [review]
Seems like windows has some problems with new model.

**Comment by daavoo** [comment]
> Seems like windows has some problems with new model.

I have no idea whats going on 😅

**Comment by skshetry** [comment]
`Trainer` is using `time.time()` which has a very low resolution in Windows. So I think `time.time() - start_time` becomes `0`. Try adding a `time.sleep()` to the minimum resolution.
```python
time.sleep(time.get_clock_info('time').resolution)
```

**Comment by skshetry** [comment]
Or, propose a fix in `transformers` to move away from `time.time()`. 😅

**Pull request merged**
