### PR TITLE
fix(studio): wait for studio metrics publish to complete on end

### PR DESCRIPTION
**Pull request by shcheklein**
W/o this fix in the `example-get-started-experiments` we are not getting images published to Studio (it doesn't have time to complete, `evaluate` exits faster).

--------------

- [X] ❗ I have followed the [Contributing to DVCLive](https://github.com/iterative/dvclive/blob/main/CONTRIBUTING.rst) guide.

- [X] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Thank you for the contribution - we'll try to review it as soon as possible. 🙏

### CODE REVIEW

**Comment by dberenbaum** [comment]
Looking at the [discussion](https://github.com/iterative/dvclive/pull/814/files#r1572688608) from when we added threads, I think this was intentional and is why the thread has `daemon=True`. Some questions:

1. Does dropping `daemon=True` accomplish the same thing?
2. What happens if any call to Studio hangs? I think that was why I added `daemon=True`.
3. Could we make a final `data` post to Studio in the main thread? That would ensure the final data is posted without needing every post to return.

**Comment by shcheklein** [comment]
> Looking at the [discussion](https://github.com/iterative/dvclive/pull/814/files#r1572688608) from when we added threads, I think this was intentional and is why the thread has daemon=True. Some questions:

Right, but at the end of the process if becomes unpredictable / we are losing data ... not sure this is expected tbh ...

> Does dropping daemon=True accomplish the same thing?

We would need probably then a way to signal that thread to complete?

> Does dropping daemon=True accomplish the same thing?

In this case it be waiting _only_ at the end ... we can probably put some timeout? But as far as I understand we already do have some timeouts on post to studio call. So, it should not be infinite ...

> That would ensure the final data is posted without needing every post to return.

Could you clarify please? Not sure how this idea is easier / can help tbh ...

**Review by dberenbaum — APPROVED** [review]
If we already have some timeouts for Studio posts, I'm fine to merge this. I assume it should be no worse than what we had before threads.

**Comment by shcheklein** [comment]
I assume that timeout is specified here:

```python
response = requests.post(
            url,
            json=body,
            headers={
                "Content-type": "application/json",
                "Authorization": f"token {token}",
            },
            timeout=(30, 5),
        )
```

**Pull request merged**
