### PR TITLE
Add `pathlib` path support with test

### LINKED ISSUE #428: Support for `pathlib` paths
Doing this `DVCLiveCallback(dir=Path("results")/"train", ...)` errors out with:
```
TypeError: Exception occured in `DVCLiveCallback` when calling event `after_fit`:
	argument of type 'PosixPath' is not iterable
```

(`DVCLiveCallback(dir="results/train", ...)` works)

### PR DESCRIPTION
**Pull request by swarajpande4**
- [x] ❗ I have followed the [Contributing to DVCLive](https://github.com/iterative/dvclive/blob/master/CONTRIBUTING.md)
  guide.

- [x] 📖 If this PR requires [documentation](https://dvc.org/doc) updates, I have created a separate PR (or issue, at least) in [dvc.org](https://github.com/iterative/dvc.org) and linked it here.

Resolves #428

### CODE REVIEW

**Review by daavoo — CHANGES_REQUESTED** [review]
Hi @swarajpande4 , thanks for the contribution!

Could you please include a test that reproduces the bug?
The last time I tried, I was not able to reproduce it

**Comment by swarajpande4** [comment]
Hi @daavoo ,
I was not able to reproduce the bug few days before creating the PR. Hence, I added the above code which acts as a safety net for `pathlib` Path objects. 
I'll try to reproduce the bug on my local, however if bug is now resolved (maybe due to some updates in `pathlib` module) and does not reproduce on my local either, then I believe the PR and the issue can be closed. Thanks.

**Comment by daavoo** [comment]
> Hi @daavoo , I was not able to reproduce the bug few days before creating the PR. Hence, I added the above code which acts as a safety net for `pathlib` Path objects. I'll try to reproduce the bug on my local, however if bug is now resolved (maybe due to some updates in `pathlib` module) and does not reproduce on my local either, then I believe the PR and the issue can be closed. Thanks.

Thanks, @swarajpande4 , appreciate the work

**Comment by swarajpande4** [comment]
Hey @daavoo, 
I tried replicating the bug by using `dir=Path('dvclive')/'results'` in `Live` and `DVCLiveCallback` objects but found no errors, and the objects are working fine as well. Hence, I would suggest to close #428 with this PR as well. 
Thanks for the review.

**Pull request closed without merging**
