### PR TITLE
Require DVC >2.45.1

### PR DESCRIPTION
**Pull request by daavoo**
To unbreak to live-experiments, see https://github.com/iterative/studio/issues/5259 for context

### CODE REVIEW

**Comment by dberenbaum** [comment]
Do we first need to drop dvclive from the dvc deps to avoid a circular dependency?

**Review by dberenbaum — APPROVED** [review]

**Review by daavoo — COMMENTED** [review]
Pending of a new DVC release

**Comment by dberenbaum** [comment]
Should we also update the min DVC version required here? I guess it should require 2.45.2?

**Comment by daavoo** [comment]
> Should we also update the min DVC version required here? I guess it should require 2.45.2?

Just updated the requirement to `dvc>2.45.1`

**Pull request merged**
