### PR TITLE
report: Add `notebook` mode.

### LINKED ISSUE #309: `report`: render inline in ipython
Render the report inline within a notebook instead of in a separate HTML/mardown document. Should be prioritized after we have a basic DVCLive-only workflow for parameters/metrics/plots.

### PR DESCRIPTION
**Pull request by daavoo**
Renders existing HTML report inside an IFrame and updates it on each next_step.

Closes #309

---

https://user-images.githubusercontent.com/12677733/217227396-5ea5f552-bd9c-460a-8ebb-66892a969413.mp4

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
I need to add tests and manually try the different frameworks but I think it is ready to play around @dberenbaum 

It kind of highlights the need for https://github.com/iterative/dvc-render/issues/21
Also unsure about the values to hardcode the size of the IFrame

**Comment by shcheklein** [comment]
@daavoo cool! could you please do a brief screen recording to see how it looks? (no voice of course, kinda live screenshot :) )

**Comment by dberenbaum** [comment]
@daavoo Does it work for you locally in [https://github.com/iterative/dvc-get-started-cv with](https://github.com/iterative/dvc-get-started-cv/tree/1-notebook-dvclive)? At first I get what looks like maybe an empty report:

Screenshot 2023-01-27 at 1 37 22 PM

Later I get a 404:

Screenshot 2023-01-27 at 1 39 00 PM

I was having trouble rendering when I played around with it last month, so it's possible it's an issue on my end.

**Comment by daavoo** [comment]
> @daavoo cool! could you please do a brief screen recording to see how it looks? (no voice of course, kinda live screenshot :) )

Added a recording to P.R. description.

**Comment by daavoo** [comment]
> Does it work for you locally in [https://github.com/iterative/dvc-get-started-cv with](https://github.com/iterative/dvc-get-started-cv/tree/1-notebook-dvclive)?

It does work for me.

> I was having trouble rendering when I played around with it last month, so it's possible it's an issue on my end.

Could you check for errors in the browser JS console?

Where are you calling `jupyter notebook` from?

**Comment by daavoo** [comment]
> @daavoo Does it work for you locally in [https://github.com/iterative/dvc-get-started-cv with](https://github.com/iterative/dvc-get-started-cv/tree/1-notebook-dvclive)? At first I get what looks like maybe an empty report:

That is just a placeholder `IPython.display` I added on `Live.init` to ensure that the report is always on top and doesn't mess up with the other logs/plugins.

 I can remove `DVCLive Report` in favor of an empty string.
 
> Later I get a 404:

The issue is the `os.chdir` performed at the beginning of the notebook.
I will update the notebook in https://github.com/iterative/example-repos-dev/pull/161

**Comment by shcheklein** [comment]
> Added a recording to P.R. description.

🙏 

Q: do we want this to be enabled by default? Feels a bit too intrusive (and it'll overlap with VS Code, Studio monitoring, etc). I think it would be great to log options when you run an experiment, .e.g:

```
If you want to see report you can do one this:

- embed into Notebooks ...
- VS Code ...
- Studio ....
```

wdyt?

**Comment by dberenbaum** [comment]
Thanks @daavoo! Seems to work for me on other repos. Here's a more realistic demo (using https://github.com/iterative/lstm_seq2seq with tweaked params to run faster) to see how it interacts with other notebook outputs:

https://user-images.githubusercontent.com/2308172/215843310-5b12a7f9-0667-4c7a-98ef-5c449757b9d4.mov

At the end, I saw some repeated "blinking." Could `make_report` be called many times at the end for some reason?

https://user-images.githubusercontent.com/2308172/215843620-30a110c3-c1c7-4028-a4cf-5b5236a57b0e.mov

**Comment by daavoo** [comment]
> to see how it interacts with other notebook outputs:

um. looks like the instantiation of the callback (and thus `Live` object) is being delayed there. 
That is unfortunate, as the placeholder IPython.display doesn't do the trick.
Could you try manually instantiating `Live` object outside and passing it to the callback?

**Comment by daavoo** [comment]
> At the end, I saw some repeated "blinking." Could make_report be called many times at the end for some reason?

Will take a look using the repo

**Comment by dberenbaum** [comment]
> Q: do we want this to be enabled by default? Feels a bit too intrusive (and it'll overlap with VS Code, Studio monitoring, etc). I think it would be great to log options when you run an experiment, .e.g:

🤔 @shcheklein Can you explain more what you would expect all the options to say? Could you turn the message off? Is it specific to this notebook mode, or should it apply to any mode? What do you see as the default onboarding workflow for both VS Code and non-VS Code users to see live metrics?

**Comment by daavoo** [comment]
> Q: do we want this to be enabled by default? Feels a bit too intrusive (and it'll overlap with VS Code, Studio monitoring, etc). 

This is enabled in `auto` mode. For those overlaps, we could chose to not use the `notebook` display if there are signals that we are overlapping.

For Studio monitoring should be doable because DVCLive has the info available. For VSCode I am not sure if there is an easy way for DVCLive to detect that the DVC extension is enabled

**Comment by dberenbaum** [comment]
@daavoo Can we clean up the table? If we want to keep any kind of HTML output, it seems like this would go a long way towards making it feel more polished.

**Comment by dberenbaum** [comment]
> um. looks like the instantiation of the callback (and thus `Live` object) is being delayed there. That is unfortunate, as the placeholder IPython.display doesn't do the trick until `Live` gets instantiated.

It's delayed because it is set up to only log every 50 steps.

> To verify, could you try manually instantiating `Live` object outside and passing it to the callback?

Sure. It does generate the placeholder immediately. Not sure if that looks any better?

https://user-images.githubusercontent.com/2308172/215854435-de93dd18-e3d3-42e8-8520-efb18353ab35.mov

**Comment by daavoo** [comment]
> It's delayed because it is set up to only log every 50 steps.

I mean that in some frameworks the `Live` object is instantiated when the callback is instantiated but lightning uses that `experiment` property that appears to be delayed until needed.
I think we could change this in our logger, though .

> Sure. It does generate the placeholder immediately. Not sure if that looks any better?

Yeah I know it doesn't matter right now 😅 

However, the point is that the placeholder could be actually a not so ugly HTML of equal size to the future IFrame so the space is clearly reserved in the output, and it doesn't interfere with progressbars or whatever output the framework might generate

**Comment by shcheklein** [comment]
> 🤔 @shcheklein Can you explain more what you would expect all the options to say? 

List of things you can do to see actual live updates:

- If you are in nobebook ... adding an option to `live` object (e.g. "render=True")...
- use Studio (a link to docs)
- install VS Code extension (link to the marketplace)

> Could you turn the message off?

Yes.

> Is it specific to this notebook mode, or should it apply to any mode?

Any mode

> What do you see as the default onboarding workflow for both VS Code and non-VS Code users to see live metrics?

Same as today + a message that would help navigating.

------

To me rendering an HTML like this inside notebook by default feels a bit too intrusive. It overlaps potentially with VS Code in some cases (ppl can get confused). Even if we go that path we should at least also show how to disable this in the HTML itself.

**Comment by daavoo** [comment]
> To me rendering an HTML like this inside notebook by default feels a bit too intrusive.

Is your concern about how it is implemented (`IFrame`), about the space that it takes, or both?

> It overlaps potentially with VS Code in some cases (ppl can get confused).

If I understand correctly, the scenario overlapping would be someone with the VSCode editor and the DVC extension installed, running the notebook inside a Git+DVC Repo (`dvc init` has been run), right?

I might be wrong but I see that scenario as far less likely than any others like Google Colab, Kaggle Notebooks, Jupyterlab servers, or just people running the notebook without meeting the above conditions (running local notebooks outside a Git Repo is also common)

I think for the overlapping scenario, the best would be to figure out how to get a signal that the VSCode and DVC extension are up and running (dvc extension could expose env var maybe?).

**Comment by shcheklein** [comment]
> Is your concern about how it is implemented (IFrame), about the space that it takes, or both?

Neither :).

It just doesn't feel right (by default). Fels a bit too much of a side effect from running the code by default. Are there any other examples that come to your mind that would by default do similar things?

E.g. W&B could have potentially embedded an IFrame into the notebook by default as well.

My expectation when I run my code is to see the regular output that is usually expected and produced by the framework itself. Our additional output should be interfering with it much I think.

**Comment by dberenbaum** [comment]
> E.g. W&B could have potentially embedded an IFrame into the notebook by default as well.

For context, here's what W&B does (note that I can't get the example repo to work): https://docs.wandb.ai/guides/track/jupyter

Anyway, let's discuss auto behavior as a follow-up and not block the rest of the PR? We can merge without making it part of auto since that will be the less intrusive option while we discuss it.

**Comment by shcheklein** [comment]
So, for W&B you need to:

```
... start a new cell with %%wandb to see live graphs in the notebook. 
```

> Anyway, let's discuss auto behavior as a follow-up and not block the rest of the PR? We can merge without making it part of auto since that will be the less intrusive option while we discuss it.

sounds good to me!

**Comment by daavoo** [comment]
Updated the P.R.

@shcheklein Behavior is only enabled if `report=notebook`. 

@dberenbaum Updated the init placeholder to take the same space as the subsequent IFrame so the space gets "reserved" on init and it doesn't mess up with existing logs because of the resizing that was happening before.

Let's discuss improvements to appearance as a follow-up in https://github.com/iterative/dvc-render/issues/21 unless we consider it a blocker to merge this.

**Review by dberenbaum — APPROVED** [review]

**Pull request merged**
