### PR TITLE
live: Rename `log` to `log_metric`.

### LINKED ISSUE #336: `log`: make `log_metric` alias?
Not sure why anyone would want a longer method, but `log_metric` is more explicit. Is it worth adding for clarification?

### PR DESCRIPTION
**Pull request by daavoo**
Closes #336

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
@dberenbaum went for replacing instead of alias because of https://github.com/iterative/dvclive/issues/336#issuecomment-1293352694. 
At this point where we have all the other methods named like `log_{x}` so `log` might look like a particular case for logging anything (we could consider actually implementing a `log` for anything but that would be a separate request)

**Comment by dberenbaum** [comment]
I guess now is the time to do it 😄

**Comment by dberenbaum** [comment]
One thought here: since I consider this a pretty severe breaking change, can we leave an unimplemented `log` method that raises an exception telling users it's been changed to `log_metric`?

**Comment by daavoo** [comment]
> One thought here: since I consider this a pretty severe breaking change, can we leave an unimplemented `log` method that raises an exception telling users it's been changed to `log_metric`?

I guess I can just add the alias instead as it would take as much code

**Comment by dberenbaum** [comment]
> I guess I can just add the alias instead as it would take as much code

I think that depends on how much you worry that `log` may cause confusion, or if you think we need to reuse `log` for something in the near future.

**Comment by daavoo** [comment]
> I think that depends on how much you worry that log may cause confusion, 

I don't worry that much, but the thing is that I don't see any benefit of keeping `log` apart from the fact that removing it is a breaking change. Given that 1.0 is full of those, sounds like the time to remove it.

> or if you think we need to reuse log for something in the near future.

A general purpose `log` similar to `wandb.log` would be a breaking change to the API if we keep the current backward compatible `log`.

**Review by dberenbaum — APPROVED** [review]
I'm fine with whatever you decide here.

**Comment by skshetry** [comment]
What about `log_metrics`? Is that required?

**Comment by daavoo** [comment]
> What about `log_metrics`? Do we need that too?

https://github.com/iterative/dvclive/issues/350

**Pull request merged**
