### PR TITLE
Revisit frameworks naming.

### PR DESCRIPTION
**Pull request by daavoo**
Replace `dvclive` arg with `live`.
Rename `DvcLive` to `DVCLive`.

### CODE REVIEW

**Comment by daavoo** [comment]
To be optionally revisited during doc review

**Comment by shcheklein** [comment]
We need to update https://github.com/open-mmlab/mmcv ?

(docs for the `live` arg is on my todo list, I'm waiting for things to settle a bit)

**Comment by daavoo** [comment]
> We need to update https://github.com/open-mmlab/mmcv ?

Yes, but I am waiting on 1.0 to send a P.R. with all related changes.

> (docs for the `live` arg is on my todo list, I'm waiting for things to settle a bit)

I already included it as part of 1.0 branch

**Comment by shcheklein** [comment]
> I already included it as part of 1.0 branch

🙏

**Pull request merged**
