### PR TITLE
use setuptools_scm

### PR DESCRIPTION
**Pull request by dtrifiro**

### CODE REVIEW

**Comment by skshetry** [comment]
@dtrifiro, I propose migrating to py-template straight away. Let me know if you need any help, I did that last week with scmrepo.

**Comment by skshetry** [comment]
Related: https://github.com/iterative/dvclive/issues/272

**Comment by dtrifiro** [comment]
>  @dtrifiro, I propose migrating to py-template straight away. Let me know if you need any help, I did that last week with scmrepo.
Yeah, I think it's worth it.

**Comment by dtrifiro** [comment]
Superseded by #281

**Pull request closed without merging**
